export const BLOCKED_EMAIL_DOMAINS = [
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'guerrillamail.de',
  'sharklasers.com',
  'grr.la',
  'spam4.me',
  'tempmail.com',
  'temp-mail.org',
  'tempmail.io',
  'throwaway.email',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  '10minutemail.com',
  '10minutemail.net',
  '20minutemail.com',
  'guerrillamailblock.com',
  'trashmail.com',
  'dispostable.com',
  'mailnesia.com',
  'getnada.com',
  'getairmail.com',
  'maildrop.cc',
  'tempail.com',
  'mailcatch.com',
  'mailinator2.com',
  'mytrashmail.com',
  'trashmail.io',
  'fakemailgenerator.com',
  'fakeinbox.com',
  'spambog.com',
  'spamgourmet.com',
  'mintemail.com',
  'jetable.org',
  'spambox.us',
  'mailmetrash.com',
  'mailmoat.com',
  'deadaddress.com',
  'spamhole.com',
  'spamstack.net',
  'trashymail.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
] as const;

export type BlockedEmailDomain = typeof BLOCKED_EMAIL_DOMAINS[number];

export function isEmailDomainBlocked(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  return domain ? BLOCKED_EMAIL_DOMAINS.includes(domain as BlockedEmailDomain) : false;
}